# Generated by Django 6.0.4 on 2026-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=200)),
                ('pershkrimi', models.TextField(blank=True, null=True)),
                ('kodi_produktit', models.CharField(max_length=50, unique=True)),
                ('sasia', models.IntegerField(default=0)),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
