# Generated by Django 6.0.4 on 2026-04-11 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazina', '0002_produkti_qr_kodi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkti',
            old_name='cmimi',
            new_name='cmimi_blerjes',
        ),
        migrations.RenameField(
            model_name='produkti',
            old_name='data_krijimit',
            new_name='krijuar_me',
        ),
        migrations.RemoveField(
            model_name='produkti',
            name='kodi_produktit',
        ),
        migrations.RemoveField(
            model_name='produkti',
            name='pershkrimi',
        ),
        migrations.RemoveField(
            model_name='produkti',
            name='qr_kodi',
        ),
        migrations.AddField(
            model_name='produkti',
            name='cmimi_ofertes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produkti',
            name='cmimi_shitjes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkti',
            name='data_skadences',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkti',
            name='furnitori',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produkti',
            name='krijuar_nga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produkti',
            name='ne_oferte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produkti',
            name='njesia_matese',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('L', 'Litër'), ('COPE', 'Copë'), ('KUTI', 'Kuti')], default='COPE', max_length=10),
        ),
        migrations.AddField(
            model_name='produkti',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='produkti',
            name='stoku_minimal',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='sasia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
