# Generated by Django 6.0.4 on 2026-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazina', '0003_rename_cmimi_produkti_cmimi_blerjes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkti',
            name='monedha',
            field=models.CharField(choices=[('ALL', 'Lek'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='ALL', max_length=3),
        ),
    ]
