# Generated by Django 6.0.4 on 2026-04-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazina', '0004_produkti_monedha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkti',
            name='cmimi_blerjes',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='cmimi_ofertes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='cmimi_shitjes',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='sasia',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='stoku_minimal',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=10),
        ),
    ]
